acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/',views.update, name="update"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('acc/',include('acc.urls')),
    path('product/', include("product.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
]

product/urls.py
from django.urls import path
from . import views


app_name = "product"
urlpatterns =[
    path('index/', views.index, name="index"),
    path('detail/<bpk>', views.detail, name="detail"),
    path('delete/<bpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('update/<bpk>', views.update, name="update"),
    # path('creply/<bpk>', views.creply, name="creply"),
    # path('dreply/<bpk>/<rpk>', views.dreply, name="dreply"),
]

acc/models.py

from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser): 
    pass

main/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from acc.models import User

# Create your models here.

class Product(models.Model):
    subject = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    picture = models.ImageField(upload_to= "product/", blank=True, null=True)

    def summary(self):
        if len(self.content) > 20:
            return f"{self.content[:20]} ...자세히 보기"
        return self.content

    def __str__(self):
      return f"{self.subject}_{self.writer}"

    def getpic(self):
        if self.picture:
            return self.picture.url
        return "/media/noimage.jpg"


# class Reply(models.Model):
#     board = models.ForeignKey(Product, on_delete=models.CASCADE)
#     replyer = models.ForeignKey(User, on_delete=models.CASCADE)
#     comment = models.TextField()

#     def __str__(self):
#       return f"{self.product}_{self.replyer}"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User

def index(request):
    return render(request,'acc/index.html')
# Create your views here.

def login_user(request):
    if request.method == "POST" :
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u : 
            login(request,u) 
            return redirect("acc:index")

    return render(request,'acc/login.html')

def logout_user(request):
    logout(request)  
    return redirect("acc:index")

def profile(request):
    return render(request, "acc/profile.html")

def delete(request):
    request.user.delete()
    return redirect("acc:index") 

def signup(request):
    if request.method=="POST":
        un = request.POST.get("uname")
        up = request.POST.get("upass")
        ue = request.POST.get("umail")
        uf = request.POST.get("fname")
        ul = request.POST.get("lname")
        User.objects.create_user(username=un, password=up, email=ue,
        first_name=uf, last_name=ul)
        return redirect("acc:index")
    return render(request,"acc/signup.html")       

def update(request):
    if request.method=="POST":
        u = request.user
        un = request.POST.get("uname") 
        ue = request.POST.get("umail")
        uf = request.POST.get("fname")
        ul = request.POST.get("lname")    
        u.email = ue
        u.first_name = uf
        u.last_name = ul
        u.save()

    return render(request,"acc/update.html")

main/views.py
from django.shortcuts import render


def index(request):
    return render(request,'acc/index.html')

product/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.utils import timezone
from django.core.paginator import Paginator
# Create your views here.


def index(request):
    pg = request.GET.get("page", 1)
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")

    if kw:
        if cate == "sub":
            b = Product.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            from acc.models import User
            try:
                u = User.objects.get(username=kw)
                b = Product.objects.filter(writer=u)
            except:
                b = Product.objects.none()
        elif cate == "con":
            b = Product.objects.filter(content__contains=kw)
        else:
            b = Product.objects.none()
    else:
        b = Product.objects.all()

    pag = Paginator(b, 5)
    obj = pag.get_page(pg)
    context = {
        "bset": obj,
        "cate": cate,
        "kw": kw,
        "b": b
    }
    return render(request, "product/index.html", context)




def update(request, bpk):
    b = Product.objects.get(id=bpk)

    if b.writer != request.user:
        return redirect("product:index")

    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject = s
        b.content = c
        b.save()
        return redirect("product:detail", bpk)
    context = {
        "b":b
    }
    return render(request, "product/update.html", context)

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        pi = request.FILES.get("pic")
        Product(subject=s, content=c, picture=pi,
        writer=request.user, pubdate=timezone.now()).save()
        print(Product.objects.all())
        return redirect("product:index")
    return render(request, "product/create.html")

def delete(request, bpk):
    b = Product.objects.get(id=bpk)
    if request.user == b.writer:        
        b.picture.delete()
        b.delete()
    else:
        pass 
    return redirect("product:index")

def detail(request, bpk):
    b = Product.objects.get(id=bpk)
    # r = b.reply_set.all()
    context = {
        "b": b,
        # "rset" : r
    }
    return render(request, "product/detail.html", context )


# def dreply(request, bpk, rpk):
#     r = Reply.objects.get(id=rpk)
#     if r.replyer == request.user:
#         r.delete()
#     else:
#         pass 
#     return redirect("product:detail", bpk)


# def creply(request, bpk):
#     b = Product.objects.get(id=bpk)
#     c = request.POST.get("com")
#     Reply(board=b, replyer=request.user, comment=c).save()
#     return redirect("product:detail", bpk)


templates/acc/index.html
{% extends 'base.html' %}
{% block con %}
    <div class="p-5 mb-2 bg-light rounded-3">
        <h1 class="display-5 fw-bold">KG Commerce</h1>        
               
{% if request.user.is_authenticated %}
<!-- 인증된 사용자 -->
        {{ request.user }} 님 !! Have a good day ! <br><br> 
        <a href="{% url 'acc:profile' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">PROFILE</button></a>
        <a href="{% url 'acc:logout' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">LOGOUT</button></a>

{% else %}
<!-- 익명의 사용자 -->        
        KG Commerce에 오신 것을 환영합니다 ! <br><br>                
        <a href="{% url 'acc:login' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;">LOGIN</button></a>
        <a href="{% url 'acc:signup' %}"><button class="btn btn-dark btn-lg" type="button" style="font-weight: bold;" >SIGN UP</button></a>
    

{% endif %}
    </div>
    <form>
        <div class="container">
            <div class="row"> 
                <div class="col-lg-3"> <h3 class="display-6 fw-bold"> KG Commerce </h3> 
                </div>
                <div class="col-lg-7">
                    <input type="text" name="kw" value="{{kw}}" class="form-control">
                </div>
                <div class="col-lg-2 text-center">
                    <a href="{% url 'product:index' %}" name="kw" value="{{kw}}"><button class="btn btn-dark" type="button">찾아보기</button></a>
                </div>
            </div>
        </div>    
    </form>
{% endblock %}
    

templates/acc/login.html
{% extends 'base.html' %}
{% block con %}

<div class="text-center">
    <br><br>
    <h1 class="display-10 fw-bold">KG Commerce에 오신 것을 환영합니다!</h1>
    <br>

    

    <form method="post">
        {% csrf_token %}
        <input type="text" name="uname" placeholder="Input your ID"><br><br>
        <input type="password" name="upass" placeholder="Input yout Password"><br><br>
        <button class="btn btn-dark btn-secondary" style="font-weight: bold;">LOGIN</button>


        <a href="{% url 'acc:index' %}"><button class="btn btn-dark btn-secondary" type="button" style="font-weight: bold;">HOME</button></a>

    </form>
</div>


{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}
{% block con %}


<h1>{{ user }}'s profile</h1>

USERNAME <input type="text" value = "{{user.username}}" disabled><br><br>
EMAIL <input type="text" value = "{{user.email}}" disabled><br><br>
FIRST NAME <input type="text" value = "{{user.first_name}}"disabled><br><br>
LAST NAME <input type="text" value = "{{user.last_name}}" disabled><br><br>
<a href="{% url 'acc:index' %}"><button>HOME</button></a>
<a href="{% url 'acc:update' %}"><button>MOD</button></a>
<a href="{% url 'acc:delete' %}"><button>DEL</button></a>

{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}
{% block con %}
<br><br>

<div class="text-center">
    <h1 class="display-10 fw-bold">회원 가입</h1><br>

    <form method="post">
        {% csrf_token %}
        ID : <input type="text" name="uname" placeholder="input your ID"><br><br>
        PW : <input type="password" name="upass" placeholder="input your P/W"><br><br>
        Email : <input type="text" name="umail" placeholder="example@example.com"><br><br>
        이름 : <input type="text" name="fname" placeholder="길동"><br><br>
        성 : <input type="text" name="lname" placeholder="홍"><br><br>
        <button class="btn btn-dark btn-secondary" style="font-weight: bold;">가입</button>
    </form>
</div>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}
{% block con %}

<h1>{{ user }}'s UPDATE PAGE</h1>

<form method="post">
    {% csrf_token %}
USERNAME <input type="text" name="uname" value="{{ user }}" disabled><br><br>
PASSWORD <input type="password" name="upass"><br><br>
EMAIL <input type="text" name="umail" value="{{ user.email }}"><br><br>
FIRST_NAME<input type="text" name="fname" value="{{ user.first_name }}"><br><br>
LAST_NAME<input type="text" name="lname" value="{{ user.last_name }}"><br><br>

<button class="btn btn-dark btn-secondary" style="font-weight: bold;">등록</button>
</form>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>KG Commerce</title>
    </head>
    <body>

        {% if user.is_authenticated %}
            <!-- 인증된사용자 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'product:index' %}">Product</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user }}
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'acc:profile' %}">PROFILE</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% else %}
            <!-- 익명의사용자 -->
            <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(0, 0, 0); font-size: 20px; font-weight: bold;">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'acc:index' %}">HOME</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'product:index' %}">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:login' %}">LOGIN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'acc:signup' %}">SIGNUP</a>
                            </li>
                            
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}

        
        {% block con %}
            
        {% endblock %}
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>    
    </body>
</html>

templates/product/create.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글 작성</b></h1>
        <form method="post" action = "{% url 'product:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" class="form-control">
            </div>
            <div class="mb-3">
              <label class="form-label">Image</label>
              <input type="file" name="pic" class="form-control" >
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" value="{{ user }}" disabled>
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 150px;"></textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">생성</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/product/detail.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5">
        <h1><b>{{b.subject}}</b></h1>

        <div class="row mt-5">
            
            <div class="col-lg-1">
            </div>

            <div class="col-lg-4">
                <img src= "{{ b.getpic }}" style = "width: 350px; height: 350px;" >
            </div>
            <div class="col-lg-4">
                <textarea class="form-control" style="height: 350px;" disabled>{{ b.content }}</textarea>
            </div>
            
            <div class="col-lg-2" style="margin: auto;">
                <div class="text-center mt-1">
                    <h4>판매자 : <b>{{ b.writer }}</b></h4>
                </div>
                <div class="text-end mt-2" style="font-size:small">
                    등록일 : {{ b.pubdate | date:'Y년 n월 j일 H:i' }} 
                </div>
            </div>
        </div>


        <div class="mt-3 text-end">
            <a href="{% url 'product:index' %}" class="btn btn-dark">메인</a>
            {% if user == b.writer %}
                <a href="{% url 'product:update' b.id %}"><button class="btn btn-secondary">수정</button></a>
                <a href="{% url 'product:delete' b.id %}"><button class="btn btn-danger">삭제</button></a>
            {% endif %}
        </div>


        <hr>

        
    </div>

{% endblock %}

templates/product/index.html
{% extends 'base.html' %}
{% block con %}
{% load mathfilters %}
    <div class="container mt-5 mb-5">
        <h1><b>KG Commerce Product</b></h1>

        <div class="text-end">
            <a href="{% url 'product:create' %}" class="btn btn-dark">CREATE</a>
        </div>


        <!-- 테이블 -->
        <table class="table mt-3 table-hover">
            <thead style="background-color: black; color:white; font-size: 20px;">
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">Image</th>
                    <th scope="col">SUBJECT</th>
                    <th scope="col">SUMMARY</th>
                    <th scope="col">WRITER</th>
                </tr>
            </thead>
            <tbody>
                {% if b %}
                    {% for i in b %}
                        <tr>
                            <th scope="row">{{ bset.start_index|add:forloop.counter0 }}</th>
                            <td><img src= "{{ i.getpic }}" style = "width: 80px; height: 80px;" ></td>
                            <td><a class="sub" href="{% url 'product:detail' i.id %}">{{ i.subject }}</a></td>
                            <td>{{ i.summary }}</td>
                            <td>{{ i.writer }}</td>
                            
                        </tr>
                    {% endfor %}
                {% else %}
                    {% if kw %}
                        <tr class="text-center">
                            <th colspan="5"><h3><b>검색결과가 없습니다.</b></h3></th>
                        </tr>
                    {% else %}
                        <tr class="text-center">
                            <th colspan="5">등록된 제품이 존재하지 않습니다.</th>
                        </tr>
                    {% endif %}
                {% endif %}
            </tbody>
        </table>

        <nav id="pag" class="mt-5" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">

                {% if bset.has_previous %}
                    <li class="page-item">
                        <a href="?page=1&cate={{cate}}&kw={{kw}}" class="page-link">처음</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}" class="page-link">이전</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">처음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">이전</a>
                    </li>
                {% endif %}
                

                {% for i in bset.paginator.page_range %}
                    {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
                        <li class="page-item {% if bset.number == i %} active {% endif %}">
                            <a class="page-link" href="?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if bset.has_next %}
                    <li class="page-item">
                        <a href="?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}" class="page-link">다음</a>
                    </li>
                    <li class="page-item">
                        <a href="?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}" class="page-link">마지막</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">다음</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">마지막</a>
                    </li>
                {% endif %}

            </ul>
        </nav>

        <form>
            <div class="row mt-4"> 
                <div class="col-lg-2">
                    <select class="form-select mb-3" name="cate" aria-label=".form-select-lg example">
                        <option value="sub" {% if cate == "sub" %} selected {% endif %}>제품명</option>
                        <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                        <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                    </select>
                </div>
                <div class="col-lg-8">
                    <input type="text" name="kw" value="{{kw}}" class="form-control">
                </div>
                <div class="col-lg-2 text-center">
                    <button class="btn btn-dark">검색</button>
                    <a href="{% url 'product:index' %}" class="btn btn-dark">리셋</a>
                </div>
            </div>
        </form>









    </div>
    <style>
        .sub {
            color:black;
            text-decoration: none;
            font-size: 20px;
            font-weight: bold;
        }
        .sub:hover{
            color:red;
        }
    </style>



{% endblock %}

templates/product/update.html
{% extends 'base.html' %}
{% block con %}
    <div class="container mt-5 mb-5" style="font-size: 20px; font-weight: bold;">
        <h1><b>게시글수정</b></h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 mt-5">
                <label class="form-label">SUBJECT</label>
                <input type="text" name="sub" value="{{ b.subject }}" class="form-control">
            </div>
            <div class="mb-3">
                <label class="form-label">WRITER</label>
                <input type="text" class="form-control" disabled value="{{ b.writer }}">
            </div>
            <div class="mb-3">
                <label class="form-label">CONTENT</label>
                <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
            </div>
            <div class="text-end mt-3">
                <button class="btn btn-dark">수정</button>
            </div> 
        </form>
    </div>
{% endblock %}